spicework/config/routes.rb
Rails.application.routes.draw do
  root to: "questions#index"
  resources :answers
  resources :questions
  devise_for :user

end

spicework/app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user
end

spicework/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

spicework/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :answer
end

spicework/app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :answers
end

spicework/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :questions
end

spicework/app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  layout "application_loggedin"
  before_action :set_question, only: [:new, :create]
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @answer = @question.answers.new
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = @question.answers.new(answer_params)

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @question, notice: 'Answer was successfully created.' }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { render :new }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to answers_url, notice: 'Answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    def set_question
      @question = Question.find(
        params[:question_id] ||
        params[:answer][:question_id]
      )
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:body, :user_id, :question_id)
    end
end

spicework/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

spicework/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:body, :user_id, :answer_id)
    end
end

spicework/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  layout "application_loggedin"
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  #before_action :authenticate_user!

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:category, :body, :user_id)
    end
end

spicework/app/helpers/answers_helper.rb
module AnswersHelper
end

spicework/app/helpers/application_helper.rb
module ApplicationHelper
end

spicework/app/helpers/comments_helper.rb
module CommentsHelper
end

spicework/app/helpers/questions_helper.rb
module QuestionsHelper
end

spicework/app/views/answers/_answer_body.html.erb
<div style="border-bottom: 1px dashed #787C7E;text-align: center;">
  <strong> Answers: </strong>
</div>
<% answers.each_with_index do |answer, i| %>
  <div class="col-md-8" style="border-bottom: 1px dashed #787C7E">
    <h5 style="font-style: italic">
      <%= answer.body %>
    </h5>
    <span class="label label-default" style="color: #787C7E">
      Posted By:
      <%= answer.user.try(:email) %> |
      <% if current_user.id == answer.user_id %>
        <%= link_to 'Edit', edit_answer_path(answer) %> |
        <%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %> |
      <% end %>
      <%= answer.updated_at.strftime("%d-%b-%y %I:%M %P") %>
    </span>
  </div>
<%end%>
<div class="no_answers" style="margin-top: 10px">
  <%= "No Answers Yet." if answers.length == 0 %>
</div>

spicework/app/views/answers/_form.html.erb
<%= form_for(answer) do |f| %>
  <% if answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_area :body, style: "margin: 0px; width: 617px; height: 143px;" %>
  </div>

  <div class="field">
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="field">
    <%= f.hidden_field :question_id, value: answer.question_id || question.id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

spicework/app/views/answers/edit.html.erb
<div class="container">
  <div class="question-box">
    <h1>Editing Answer</h1>
    <%= render 'form', answer: @answer %>
  </div>
</div>

spicework/app/views/answers/new.html.erb
<div class="container">
  <div class="question-box" data-id= "<%= @question.id %>">
    <%= render 'questions/question_box', question: @question, hide_answer_btn: true %>
    <div class="answer-text-area" style="margin-top: 25px;">
      <%= render 'form', answer: @answer, question: @question %>
    </div>
  </div>
</div>

spicework/app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @answer.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @answer.user_id %>
</p>

<p>
  <strong>Question:</strong>
  <%= @answer.question.try(:body) %>
</p>

<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>

spicework/app/views/comments/_form.html.erb
<%= form_for(comment) do |f| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_field :body %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :answer_id %>
    <%= f.text_field :answer_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

spicework/app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

spicework/app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>User</th>
      <th>Answer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.body %></td>
        <td><%= comment.user_id %></td>
        <td><%= comment.answer %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

spicework/app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

spicework/app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user_id %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @comment.answer %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

spicework/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Spicework</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
</body>
</html>

spicework/app/views/layouts/application_loggedin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Spicework</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="topnavbar">
    <a href="<%= root_path%>" >
      <h2> Home</h2>
    </a>
    <%= current_user.email %> |
    <%= link_to('Logout', destroy_user_session_path, :method => 'delete') %>
  </div>
  <p class="alert"><%= alert %></p>
  <p id="notice"><%= notice %></p>
  <%= yield %>
</body>
</html>

spicework/app/views/questions/_form.html.erb
<%= form_for(question) do |f| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category %>
    <%= f.text_field :category %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body, style: "margin: 0px; width: 487px; height: 203px;" %>
  </div>

  <div class="field">
    <%#= f.label :user_id %>
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

spicework/app/views/questions/_question_box.html.erb
<div class="row">
  <span class="label label-default" style="color: #787C7E">
    Posted By:
    <%= question.user.try(:email) %>
    | Category:
    <%= question.category %> |
    <% if current_user.id == question.user_id %>
      <%= link_to 'Edit', edit_question_path(question) %> |
      <%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %> |
    <% end %>
    <%= question.updated_at.strftime("%d-%b-%y %I:%M %P") %>
  </span>
</div>
<div class="row">
  <div class="col-md-8">
    <h3>
      Q: <%= question.body %> ?
    </h3>
  </div>
  <div class="col-md-2 pull-right">
    <span class="label label-default">
    </span>
  </div>
</div>
<br>
<% unless hide_answer_btn %>
  <%= link_to '+ Write Answer', new_answer_path(question_id: question.id) %> |
  <%= "#{question.answers.count} Answers"%>
<% else %>
  Your Answer
<%end%>

spicework/app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

spicework/app/views/questions/index.html.erb
<div class="container">
  <div class="new-question" style="margin-bottom: 10px">
    <%= button_to ' + New Question ', new_question_path, class: "btn btn-info", method: :get %>
  </div>
  <% @questions.each do |question| %>
    <div class="question-box" data-id= "<%= question.id %>">
      <%= render 'question_box', question: question , hide_answer_btn: false %>
    </div>
  <% end %>
</div>
<br>


<script>
  $('.question-box').click(function() {
    let questionId = $(this).attr("data-id")
    window.location = "/questions/" + questionId;
    return true;
  })

  $(".question-box a").click(function(e) {
    e.stopPropagation();
  });

</script>

spicework/app/views/questions/new.html.erb
<div class="container">
  <div class="question-box">
    <h4>New Question</h4>

    <%= render 'form', question: @question %>

  </div>
</div>

spicework/app/views/questions/show.html.erb
<div class="container">
  <div class="question-box" data-id= "<%= @question.id %>">
    <%= render 'question_box', question: @question, hide_answer_btn: false %>
    <%= render 'answers/answer_body', answers: @question.answers %>
  </div>
</div>